# NumPy

In [3]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[0])

[1 2 3 4]


In [7]:
a.shape

(3, 4)

In [14]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.empty((2, 4))

array([[4.66694914e-310, 0.00000000e+000, 2.14321575e-312,
        8.48798317e-313],
       [1.06099790e-312, 6.79038653e-313, 8.70018275e-313,
        6.90730850e-310]])

In [27]:
np.arange(0, 20, 2) # (start, stop, step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Add, Remove, Sort

In [28]:
np.append
np.delete
np.sort

<function numpy.sort(a, axis=-1, kind=None, order=None)>

In [30]:
a = np.array([1,2,3])
np.append(a, 10)

array([ 1,  2,  3, 10])

In [32]:
a = np.append(a, 12)

In [34]:
print(a)

[ 1  2  3 12 12]


In [36]:
np.delete(a, 3)

array([ 1,  2,  3, 12])

In [38]:
a

array([ 1,  2,  3, 12, 12])

In [40]:
a = np.delete(a, 3)

In [42]:
a

array([1, 2, 3])

In [44]:
a = np.append(a, 4)

In [45]:
a

array([1, 2, 3, 4, 4])

In [46]:
a = np.delete(a, 3)

In [47]:
a

array([1, 2, 3, 4])

In [48]:
a = np.append(a, 20)

a

array([ 1,  2,  3,  4, 20])

In [49]:
a = np.append(a, 16)

a

array([ 1,  2,  3,  4, 20, 16])

In [51]:
a = np.sort(a)
a

array([ 1,  2,  3,  4, 16, 20])

In [52]:
a = np.insert(a, obj=5, values=25)
a

array([ 1,  2,  3,  4, 16, 25, 20])

In [53]:
a = np.sort(a)

In [54]:
print(a)

[ 1  2  3  4 16 20 25]


In [59]:
arr = np.array([[1,2], [3,4]])
arr.ndim

2

In [61]:
print(arr.shape)

(2, 2)


In [63]:
print(a.shape)

(7,)


In [65]:
arr2 = np.empty((2,4))

In [67]:
print(arr2)

[[4.66694914e-310 0.00000000e+000 2.14321575e-312 8.48798317e-313]
 [1.06099790e-312 6.79038653e-313 8.70018275e-313 6.90730850e-310]]


In [71]:
arr2 = arr2.reshape(4,2)

print(arr2)

[[4.66694914e-310 0.00000000e+000]
 [2.14321575e-312 8.48798317e-313]
 [1.06099790e-312 6.79038653e-313]
 [8.70018275e-313 6.90730850e-310]]


In [73]:
print(arr2)
arr2 = arr2[np.newaxis]
print(arr2.shape)

[[[4.66694914e-310 0.00000000e+000]
  [2.14321575e-312 8.48798317e-313]
  [1.06099790e-312 6.79038653e-313]
  [8.70018275e-313 6.90730850e-310]]]
(1, 1, 4, 2)


In [78]:
arr3 = np.array([[3,2,4], [7,5,3], [4,1,2]])

arr3

array([[3, 2, 4],
       [7, 5, 3],
       [4, 1, 2]])

In [80]:
print(arr3[arr3>=4])

[4 7 5 4]


In [85]:
a[0:3]

array([1, 2, 3])

In [87]:
z = np.array([[2,3], [9,7]])

x = np.array([[5,6], [7,1]])

print(z)
print(x)

[[2 3]
 [9 7]]
[[5 6]
 [7 1]]


In [90]:
c = np.vstack((z, x))
print(c)

[[2 3]
 [9 7]
 [5 6]
 [7 1]]


In [94]:
v = np.hstack((x,z))
print(v)

[[5 6 2 3]
 [7 1 9 7]]


In [101]:
zz = np.arange(0, 8, 1)
print(zz)

[0 1 2 3 4 5 6 7]


In [103]:
zz.sum()

28

In [105]:
ones = np.ones(2)
ones

array([1., 1.])

In [107]:
data = np.array([1, 2])
data

array([1, 2])

In [110]:
data * ones

array([1., 2.])

In [112]:
data * data

array([1, 4])

In [115]:
xx = np.empty(8)

In [116]:
xx

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323,
       3.0e-323, 3.5e-323])

In [117]:
xx = np.empty(2)
xx

array([1., 2.])

In [119]:
xx = np.empty((2,3))

In [121]:
xx

array([[4.66694884e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [124]:
xx = np.arange(0,9,1)

xx

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [125]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.22904093, 0.51143917],
       [0.28441471, 0.26684002],
       [0.41038997, 0.09498392]])

In [126]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.06139575 0.74929447]
 [0.86877176 0.70126812]
 [0.67766644 0.24960915]]


In [127]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [128]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [129]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [130]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [131]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [132]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [133]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [134]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [135]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [136]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [137]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [138]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [139]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [140]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [141]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [143]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [144]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [145]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [146]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [147]:
print(np.random.random((4,3,2)))

[[[0.46446754 0.45304447]
  [0.07161717 0.03454487]
  [0.28158735 0.32713951]]

 [[0.15856429 0.10559491]
  [0.25054644 0.08304057]
  [0.76373284 0.05556495]]

 [[0.83008097 0.83676531]
  [0.6967538  0.93070617]
  [0.35341521 0.86757892]]

 [[0.00697401 0.54040619]
  [0.91343402 0.93139553]
  [0.11672443 0.86459394]]]


In [148]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [149]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [151]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'observed' is not defined